import array
import hashlib
import logging
import os
import re
from collections import OrderedDict
from dataclasses import dataclass
from typing import Any

from core.gen_ai_provider import GenAIEmbedProvider
from database.connections import RAGDBConnection

logger = logging.getLogger(__name__)

MANUAL_RESET_CACHE_ON_START = False

@dataclass
class PGQLCacheHit:
    cache_id: int
    pgql: str
    strategy: str
    distance: float | None = None


class PGQLQueryCache:
    """Hybrid PGQL cache with in-memory exact hits + DB exact/semantic lookups."""

    _instance = None
    _initialized = False

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(self):
        if PGQLQueryCache._initialized:
            return
        PGQLQueryCache._initialized = True

        self.db_conn = RAGDBConnection()
        self.table_name = f"{self.db_conn.table_prefix}_pgql_cache"
        self.enable_semantic_lookup = os.getenv("PGQL_CACHE_ENABLE_SEMANTIC_LOOKUP", "true").lower() == "true"
        self.semantic_threshold = float(os.getenv("PGQL_CACHE_SEMANTIC_THRESHOLD", "0.12"))
        self.semantic_top_k = int(os.getenv("PGQL_CACHE_SEMANTIC_TOP_K", "1"))
        self.max_memory_entries = int(os.getenv("PGQL_CACHE_MEMORY_MAX_ENTRIES", "128"))
        self.reset_on_start = (
            MANUAL_RESET_CACHE_ON_START
            or os.getenv("PGQL_CACHE_RESET_ON_START", "false").lower() == "true"
        )
        self._memory_exact: OrderedDict[str, PGQLCacheHit] = OrderedDict()
        self._table_ready = False
        self._embed_provider: GenAIEmbedProvider | None = None
        self._reset_applied = False

    def _maybe_reset_on_start(self) -> None:
        if not self.reset_on_start or self._reset_applied:
            return
        deleted = self.clear()
        self._reset_applied = True
        logger.warning("PGQL cache reset-on-start applied. Deleted %s cached entries.", deleted)

    @staticmethod
    def normalize_question(question: str) -> str:
        lowered = str(question or "").strip().lower()
        return re.sub(r"\s+", " ", lowered)

    @staticmethod
    def normalize_pgql(pgql: str) -> str:
        text = str(pgql or "").strip()
        if text.startswith("```"):
            lines = text.split("\n")
            text = "\n".join(lines[1:-1] if lines and lines[-1] == "```" else lines[1:])
        return text.strip()

    @staticmethod
    def _sha256(value: str) -> str:
        return hashlib.sha256(value.encode("utf-8")).hexdigest()

    def _touch_memory(self, normalized_question: str, hit: PGQLCacheHit) -> None:
        if normalized_question in self._memory_exact:
            self._memory_exact.pop(normalized_question)
        self._memory_exact[normalized_question] = hit
        while len(self._memory_exact) > self.max_memory_entries:
            self._memory_exact.popitem(last=False)

    def _ensure_table(self) -> None:
        if self._table_ready:
            return

        ddl = f"""
            CREATE TABLE {self.table_name} (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                question_text VARCHAR2(4000),
                question_norm VARCHAR2(4000),
                question_hash VARCHAR2(64) NOT NULL,
                pgql_text CLOB,
                pgql_hash VARCHAR2(64) NOT NULL,
                question_embedding VECTOR,
                use_count NUMBER DEFAULT 0 NOT NULL,
                success_count NUMBER DEFAULT 0 NOT NULL,
                failure_count NUMBER DEFAULT 0 NOT NULL,
                is_active NUMBER(1) DEFAULT 1 NOT NULL,
                source VARCHAR2(64),
                last_used_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """
        unique_idx = f"""
            CREATE UNIQUE INDEX {self.table_name}_uq
            ON {self.table_name}(question_hash, pgql_hash)
        """
        question_idx = f"""
            CREATE INDEX {self.table_name}_qhash_idx
            ON {self.table_name}(question_hash)
        """

        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                for stmt in (ddl, unique_idx, question_idx):
                    try:
                        cur.execute(stmt)
                    except Exception as exc:
                        message = str(exc).upper()
                        # ORA-00955: name already used by an existing object.
                        if "ORA-00955" not in message:
                            raise
            conn.commit()

        self._table_ready = True

    def _embed_question(self, question: str) -> array.array | None:
        try:
            if self._embed_provider is None:
                self._embed_provider = GenAIEmbedProvider()
            vector = self._embed_provider.embed_client.embed_query(question)
            return array.array("f", vector)
        except Exception:
            logger.exception("Failed to embed question for PGQL cache.")
            return None

    def get_cached_pgql(self, question: str) -> PGQLCacheHit | None:
        if not question:
            return None

        self._maybe_reset_on_start()
        self._ensure_table()
        question_norm = self.normalize_question(question)
        if not question_norm:
            return None

        if question_norm in self._memory_exact:
            hit = self._memory_exact[question_norm]
            self._touch_memory(question_norm, hit)
            return PGQLCacheHit(
                cache_id=hit.cache_id,
                pgql=hit.pgql,
                strategy="memory_exact",
                distance=hit.distance,
            )

        question_hash = self._sha256(question_norm)
        exact_sql = f"""
            SELECT id, pgql_text
            FROM {self.table_name}
            WHERE question_hash = :1
              AND is_active = 1
            ORDER BY updated_at DESC
            FETCH FIRST 1 ROWS ONLY
        """

        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(exact_sql, [question_hash])
                row = cur.fetchone()
                if row:
                    hit = PGQLCacheHit(cache_id=int(row[0]), pgql=str(row[1]), strategy="db_exact")
                    self._touch_memory(question_norm, hit)
                    return hit

        if not self.enable_semantic_lookup:
            return None

        question_vec = self._embed_question(question)
        if question_vec is None:
            return None

        semantic_sql = f"""
            SELECT id, pgql_text, vector_distance(question_embedding, :1, COSINE) AS distance
            FROM {self.table_name}
            WHERE is_active = 1
              AND question_embedding IS NOT NULL
            ORDER BY distance
            FETCH FIRST {max(1, int(self.semantic_top_k))} ROWS ONLY
        """

        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(semantic_sql, [question_vec])
                row = cur.fetchone()
                if not row:
                    return None
                distance = float(row[2]) if row[2] is not None else 1.0
                if distance > float(self.semantic_threshold):
                    return None
                return PGQLCacheHit(
                    cache_id=int(row[0]),
                    pgql=str(row[1]),
                    strategy="db_semantic",
                    distance=distance,
                )

    def register_execution_outcome(self, cache_id: int, succeeded: bool) -> None:
        self._maybe_reset_on_start()
        self._ensure_table()
        delta_col = "success_count" if succeeded else "failure_count"
        sql = f"""
            UPDATE {self.table_name}
            SET use_count = use_count + 1,
                {delta_col} = {delta_col} + 1,
                last_used_at = CURRENT_TIMESTAMP,
                updated_at = CURRENT_TIMESTAMP,
                is_active = CASE
                    WHEN failure_count + CASE WHEN :1 = 0 THEN 1 ELSE 0 END >= 3
                         AND success_count = 0
                    THEN 0
                    ELSE is_active
                END
            WHERE id = :2
        """
        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(sql, [1 if succeeded else 0, cache_id])
            conn.commit()

    def store_successful_query(self, question: str, pgql: str, source: str = "llm_generated") -> None:
        self._maybe_reset_on_start()
        self._ensure_table()

        question_norm = self.normalize_question(question)
        pgql_norm = self.normalize_pgql(pgql)
        if not question_norm or not pgql_norm:
            return

        question_hash = self._sha256(question_norm)
        pgql_hash = self._sha256(pgql_norm)
        question_vector = self._embed_question(question)

        select_sql = f"""
            SELECT id
            FROM {self.table_name}
            WHERE question_hash = :1
              AND pgql_hash = :2
            FETCH FIRST 1 ROWS ONLY
        """
        update_sql = f"""
            UPDATE {self.table_name}
            SET question_text = :1,
                question_norm = :2,
                pgql_text = :3,
                source = :4,
                is_active = 1,
                updated_at = CURRENT_TIMESTAMP,
                last_used_at = CURRENT_TIMESTAMP,
                question_embedding = COALESCE(question_embedding, :5)
            WHERE id = :6
        """
        insert_sql = f"""
            INSERT INTO {self.table_name} (
                question_text,
                question_norm,
                question_hash,
                pgql_text,
                pgql_hash,
                question_embedding,
                source
            ) VALUES (:1, :2, :3, :4, :5, :6, :7)
        """
        id_lookup_sql = f"""
            SELECT id
            FROM {self.table_name}
            WHERE question_hash = :1
              AND pgql_hash = :2
            FETCH FIRST 1 ROWS ONLY
        """

        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(select_sql, [question_hash, pgql_hash])
                row = cur.fetchone()
                if row:
                    cur.execute(
                        update_sql,
                        [question, question_norm, pgql_norm, source, question_vector, int(row[0])],
                    )
                else:
                    cur.execute(
                        insert_sql,
                        [question, question_norm, question_hash, pgql_norm, pgql_hash, question_vector, source],
                    )
            conn.commit()

            with conn.cursor() as cur:
                cur.execute(id_lookup_sql, [question_hash, pgql_hash])
                id_row = cur.fetchone()
                if id_row:
                    self._touch_memory(
                        question_norm,
                        PGQLCacheHit(cache_id=int(id_row[0]), pgql=pgql_norm, strategy="db_exact"),
                    )

    def clear(self) -> int:
        self._ensure_table()
        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(f"SELECT COUNT(1) FROM {self.table_name}")
                count_row = cur.fetchone()
                count = int(count_row[0]) if count_row else 0
                cur.execute(f"DELETE FROM {self.table_name}")
            conn.commit()
        self._memory_exact.clear()
        return count

    def stats(self) -> dict[str, Any]:
        self._maybe_reset_on_start()
        self._ensure_table()
        sql = f"""
            SELECT
                COUNT(1) AS total_entries,
                SUM(CASE WHEN is_active = 1 THEN 1 ELSE 0 END) AS active_entries,
                SUM(use_count) AS total_uses,
                SUM(success_count) AS total_successes,
                SUM(failure_count) AS total_failures
            FROM {self.table_name}
        """
        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(sql)
                row = cur.fetchone() or [0, 0, 0, 0, 0]
        return {
            "total_entries": int(row[0] or 0),
            "active_entries": int(row[1] or 0),
            "total_uses": int(row[2] or 0),
            "total_successes": int(row[3] or 0),
            "total_failures": int(row[4] or 0),
            "memory_entries": len(self._memory_exact),
        }
