import array
import logging
from typing import Any

from core.gen_ai_provider import GenAIEmbedProvider
from database.connections import RAGDBConnection

logger = logging.getLogger(__name__)


def _coerce_db_text(value: Any) -> str | None:
    """Normalize Oracle CLOB/LOB values into plain Python strings."""
    if value is None:
        return None
    if hasattr(value, "read"):
        try:
            value = value.read()
        except Exception:
            return str(value)
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="ignore")
    return str(value)


class GraphSemanticCache:
    """Semantic cache for NL2Graph question -> PGQL mapping."""

    def __init__(self, db_conn: RAGDBConnection | None = None):
        self.db_conn = db_conn or RAGDBConnection()
        self.embed_provider = GenAIEmbedProvider()
        self.table_name = f"{self.db_conn.table_prefix}_nl2graph_semantic_cache"
        self._table_ready = False

    def _ensure_table(self):
        if self._table_ready:
            return

        create_stmt = f"""
            CREATE TABLE {self.table_name} (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                question VARCHAR2(4000) NOT NULL,
                pgql CLOB NOT NULL,
                answer_preview CLOB,
                embedding VECTOR,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """

        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                try:
                    cur.execute(create_stmt)
                    conn.commit()
                except Exception as exc:
                    # ORA-00955 table exists; keep going.
                    if "ORA-00955" not in str(exc):
                        raise

        self._table_ready = True

    def _embed_query(self, text: str):
        # Use the shared embedding model configured in GenAIEmbedProvider.
        emb = self.embed_provider.embed_client.embed_documents([text])[0]
        return array.array("f", emb)

    def search_similar_questions(
        self,
        question: str,
        top_k: int = 3,
        max_distance: float = 0.20,
    ) -> list[dict[str, Any]]:
        self._ensure_table()
        query_vec = self._embed_query(question)
        safe_top_k = max(1, int(top_k))

        sql = f"""
            SELECT id, question, pgql, answer_preview, vector_distance(embedding, :1, COSINE) distance
            FROM {self.table_name}
            ORDER BY distance
            FETCH FIRST {safe_top_k} ROWS ONLY
        """

        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(sql, [query_vec])
                rows = cur.fetchall()

        results = []
        for row in rows:
            distance = float(row[4]) if row[4] is not None else 1.0
            if distance <= max_distance:
                results.append(
                    {
                        "id": row[0],
                        "question": _coerce_db_text(row[1]) or "",
                        "pgql": _coerce_db_text(row[2]) or "",
                        "answer_preview": _coerce_db_text(row[3]) or "",
                        "distance": distance,
                    }
                )

        return results

    def upsert_successful_query(self, question: str, pgql: str, answer_preview: str):
        self._ensure_table()
        embedding = self._embed_query(question)

        insert_stmt = f"""
            INSERT INTO {self.table_name} (question, pgql, answer_preview, embedding)
            VALUES (:1, :2, :3, :4)
        """

        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(insert_stmt, [question[:3900], pgql, answer_preview[:3900], embedding])
            conn.commit()

    def clear_cache(self) -> int:
        """Delete all cache entries and keep table structure."""
        self._ensure_table()
        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(f"SELECT COUNT(1) FROM {self.table_name}")
                deleted_rows = int(cur.fetchone()[0] or 0)
                cur.execute(f"DELETE FROM {self.table_name}")
            conn.commit()
        return deleted_rows

    def reset_cache(self) -> int:
        """Reset cache data safely by clearing rows only."""
        return self.clear_cache()

    def cache_count(self) -> int:
        self._ensure_table()
        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(f"SELECT COUNT(1) FROM {self.table_name}")
                count = cur.fetchone()[0]
        return int(count)

    def get_cache_summary(self, limit: int = 25) -> dict[str, Any]:
        """Return safe summary information and a preview of cached entries."""
        self._ensure_table()
        safe_limit = max(1, min(int(limit), 100))
        summary: dict[str, Any] = {
            "table_name": self.table_name,
            "total_entries": 0,
            "oldest_entry_at": None,
            "newest_entry_at": None,
            "entries": [],
        }

        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    f"""
                        SELECT COUNT(1), MIN(created_at), MAX(created_at)
                        FROM {self.table_name}
                    """
                )
                count_row = cur.fetchone()
                summary["total_entries"] = int(count_row[0] or 0)
                summary["oldest_entry_at"] = _coerce_db_text(count_row[1])
                summary["newest_entry_at"] = _coerce_db_text(count_row[2])

                cur.execute(
                    f"""
                        SELECT id, question, created_at
                        FROM {self.table_name}
                        ORDER BY created_at DESC
                        FETCH FIRST {safe_limit} ROWS ONLY
                    """
                )
                rows = cur.fetchall()

        entries: list[dict[str, Any]] = []
        for row in rows:
            entries.append(
                {
                    "id": int(row[0]),
                    "question": (_coerce_db_text(row[1]) or "").strip(),
                    "created_at": _coerce_db_text(row[2]),
                }
            )

        summary["entries"] = entries
        summary["entries_returned"] = len(entries)
        return summary


class SQLSemanticCache:
    """Semantic cache for NL2SQL question -> SQL mapping."""

    def __init__(self, db_conn: RAGDBConnection | None = None):
        self.db_conn = db_conn or RAGDBConnection()
        self.embed_provider = GenAIEmbedProvider()
        self.table_name = f"{self.db_conn.table_prefix}_nl2sql_semantic_cache"
        self._table_ready = False

    def _ensure_table(self):
        if self._table_ready:
            return

        create_stmt = f"""
            CREATE TABLE {self.table_name} (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                question VARCHAR2(4000) NOT NULL,
                sql_query CLOB NOT NULL,
                answer_preview CLOB,
                embedding VECTOR,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """

        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                try:
                    cur.execute(create_stmt)
                    conn.commit()
                except Exception as exc:
                    # ORA-00955 table exists; keep going.
                    if "ORA-00955" not in str(exc):
                        raise

        self._table_ready = True

    def _embed_query(self, text: str):
        emb = self.embed_provider.embed_client.embed_documents([text])[0]
        return array.array("f", emb)

    def search_similar_questions(
        self,
        question: str,
        top_k: int = 3,
        max_distance: float = 0.20,
    ) -> list[dict[str, Any]]:
        self._ensure_table()
        query_vec = self._embed_query(question)
        safe_top_k = max(1, int(top_k))

        sql = f"""
            SELECT id, question, sql_query, answer_preview, vector_distance(embedding, :1, COSINE) distance
            FROM {self.table_name}
            ORDER BY distance
            FETCH FIRST {safe_top_k} ROWS ONLY
        """

        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(sql, [query_vec])
                rows = cur.fetchall()

        results = []
        for row in rows:
            distance = float(row[4]) if row[4] is not None else 1.0
            if distance <= max_distance:
                results.append(
                    {
                        "id": row[0],
                        "question": _coerce_db_text(row[1]) or "",
                        "sql_query": _coerce_db_text(row[2]) or "",
                        "answer_preview": _coerce_db_text(row[3]) or "",
                        "distance": distance,
                    }
                )

        return results

    def upsert_successful_query(self, question: str, sql_query: str, answer_preview: str):
        self._ensure_table()
        embedding = self._embed_query(question)

        insert_stmt = f"""
            INSERT INTO {self.table_name} (question, sql_query, answer_preview, embedding)
            VALUES (:1, :2, :3, :4)
        """

        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(insert_stmt, [question[:3900], sql_query, answer_preview[:3900], embedding])
            conn.commit()

    def clear_cache(self) -> int:
        """Delete all cache entries and keep table structure."""
        self._ensure_table()
        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(f"SELECT COUNT(1) FROM {self.table_name}")
                deleted_rows = int(cur.fetchone()[0] or 0)
                cur.execute(f"DELETE FROM {self.table_name}")
            conn.commit()
        return deleted_rows

    def reset_cache(self) -> int:
        """Reset cache, clearing rows only."""
        return self.clear_cache()

    def cache_count(self) -> int:
        self._ensure_table()
        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(f"SELECT COUNT(1) FROM {self.table_name}")
                count = cur.fetchone()[0]
        return int(count)

def get_nl2graph_semantic_cache_summary(limit: int = 25) -> dict[str, Any]:
    """Read-only utility to inspect NL2Graph semantic cache usage."""
    cache = GraphSemanticCache()
    return cache.get_cache_summary(limit=limit)