import array
import logging
from typing import Any

from core.gen_ai_provider import GenAIEmbedProvider
from database.connections import RAGDBConnection

logger = logging.getLogger(__name__)


class GraphSemanticCache:
    """Semantic cache for NL2Graph question -> PGQL mapping."""

    def __init__(self, db_conn: RAGDBConnection | None = None):
        self.db_conn = db_conn or RAGDBConnection()
        self.embed_provider = GenAIEmbedProvider()
        self.table_name = f"{self.db_conn.table_prefix}_nl2graph_semantic_cache"
        self._table_ready = False

    def _ensure_table(self):
        if self._table_ready:
            return

        create_stmt = f"""
            CREATE TABLE {self.table_name} (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                question VARCHAR2(4000) NOT NULL,
                pgql CLOB NOT NULL,
                answer_preview CLOB,
                embedding VECTOR,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """

        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                try:
                    cur.execute(create_stmt)
                    conn.commit()
                except Exception as exc:
                    # ORA-00955 table exists; keep going.
                    if "ORA-00955" not in str(exc):
                        raise

        self._table_ready = True

    def _embed_query(self, text: str):
        # Use the shared embedding model configured in GenAIEmbedProvider.
        emb = self.embed_provider.embed_client.embed_documents([text])[0]
        return array.array("f", emb)

    def search_similar_questions(
        self,
        question: str,
        top_k: int = 3,
        max_distance: float = 0.20,
    ) -> list[dict[str, Any]]:
        self._ensure_table()
        query_vec = self._embed_query(question)
        safe_top_k = max(1, int(top_k))

        sql = f"""
            SELECT id, question, pgql, answer_preview, vector_distance(embedding, :1, COSINE) distance
            FROM {self.table_name}
            ORDER BY distance
            FETCH FIRST {safe_top_k} ROWS ONLY
        """

        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(sql, [query_vec])
                rows = cur.fetchall()

        results = []
        for row in rows:
            distance = float(row[4]) if row[4] is not None else 1.0
            if distance <= max_distance:
                results.append(
                    {
                        "id": row[0],
                        "question": row[1],
                        "pgql": row[2],
                        "answer_preview": row[3],
                        "distance": distance,
                    }
                )

        return results

    def upsert_successful_query(self, question: str, pgql: str, answer_preview: str):
        self._ensure_table()
        embedding = self._embed_query(question)

        insert_stmt = f"""
            INSERT INTO {self.table_name} (question, pgql, answer_preview, embedding)
            VALUES (:1, :2, :3, :4)
        """

        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(insert_stmt, [question[:3900], pgql, answer_preview[:3900], embedding])
            conn.commit()

    def clear_cache(self):
        """Delete all cache entries and keep table structure."""
        self._ensure_table()
        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(f"TRUNCATE TABLE {self.table_name}")
            conn.commit()

    def reset_cache(self):
        """Drop and recreate semantic cache table (developer reset helper)."""
        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                try:
                    cur.execute(f"DROP TABLE {self.table_name} PURGE")
                    conn.commit()
                except Exception as exc:
                    if "ORA-00942" not in str(exc):
                        raise
        self._table_ready = False
        self._ensure_table()

    def cache_count(self) -> int:
        self._ensure_table()
        with self.db_conn.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(f"SELECT COUNT(1) FROM {self.table_name}")
                count = cur.fetchone()[0]
        return int(count)


def reset_nl2graph_semantic_cache():
    """Developer utility: drop and recreate NL2Graph semantic cache table."""
    cache = GraphSemanticCache()
    cache.reset_cache()
    logger.info("NL2Graph semantic cache was reset.")


def clear_nl2graph_semantic_cache():
    """Developer utility: clear NL2Graph semantic cache table rows."""
    cache = GraphSemanticCache()
    cache.clear_cache()
    logger.info("NL2Graph semantic cache rows were cleared.")
